version: "3.9"
services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        image: hidylima/basephp
        # image: urnau/php-community:latest
        # utilizado quando vamos contruir uma nova imagem
        networks:
            - net_principal
        volumes:
            - ./applications:/var/www
            - ./docker/nginx/sites:/etc/nginx/sites-available
        ports:
            # - "80:80" #http
            - "443:443" #https
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
            - "8084:8084"
            - "8085:8085"
            - "8086:8086"
            - "8087:8087"
            - "8088:8088"
            - "8089:8089"
        depends_on:
            - redis
            - mysql
            - node

    node:
        image: node:14 # Usando uma versão válida do Node.js
        entrypoint: /bin/sh
        ports:
            - 8010:8010
        working_dir: /var/www # Caminho absoluto no contêiner
        volumes:
            - ./:/var/www # Caminho absoluto no contêiner
        tty: true
        networks:
            - net_principal

    mysql:
        image: mysql:8.0.29-debian
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - MYSQL_VOLUME_EXEMPLO:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: projectDB
        networks:
            - net_principal
        ports:
            - 30000:3306

    redis:
        image: redis:7-alpine
        restart: always
        networks:
            - net_principal
        ports:
            - 6379:6379
networks:
    net_principal:


volumes:
    # POSTGRES_VOLUME_EXEMPLO:
    MYSQL_VOLUME_EXEMPLO:
        driver: local
